server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lajifenlei?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456


mybatis-plus:
  # xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #MP日志
  configuration:
    #标准输出，即打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.alibaba.fastjson2.support.spring

#云存储相关配置
cos:
  secret-id: AKIDpdHygFaicJn3FE0Zu1vc8VlqiNxLVSDk
  secret-key: PaopcCbmjTzKRL2YrwoSu9Ayb1DCxXt2
  #存储桶名称
  name: cos-1352695728
  #存储桶地域
  region: ap-beijing

# 微信小程序
wx:
  base-url: https://api.weixin.qq.com/
  # AppID(小程序ID)
  app-id: wxaef64a2c2670f60b
  # AppSecret(小程序密钥)
  app-secret: 33596293d010ac8bcf0fcd46469287f1

# 百度云相关
baidu:
  api-key: wSAUqyXhcpiFPg4b9pLwXIAb
  secret-key: Utdwrc21Rv5XUtqFwgrPyt0A4kCvQ1w5
  access-key: 46b2d5ebec1e4deb95817636a93f208c
  app-secret: 9a27266ea3854f4399fbb46d9a1c7b3d
  app-code: 5086d7295b6e40a88c71d3b98ac21665
